version: "3.3"

services:
  backend-api:
    image: node:12
    restart: always
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - backend
      - frontend

  frontend-app:
    image: node:12
    restart: always
    working_dir: /usr/src/app
    command: bash -c "yarn install && yarn start"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend-api
    ports:
      - 3000:3000
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  db_vol:
